language: node_js
node_js:
  - "node"
before_install:
  - sed -i 's|git@github.com:wrinkl3/slr-claiming-api-swagger.git|https://github.com/wrinkl3/slr-claiming-api-swagger.git|g' .git/config
  - cat .git/config
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
